<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <AssemblyName>EasySave</AssemblyName>
    <RootNamespace>EasySave</RootNamespace>
    <!-- Configurer la sortie pour utiliser le dossier output à la racine -->
    <OutputPath>..\output</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ApplicationIcon>Resources\easysave_cloud.ico</ApplicationIcon>
  </PropertyGroup>

  <!-- 
  <ItemGroup>
    <None Remove="Resources\easysave_icon.ico" />
  </ItemGroup>
  -->

  <!-- 
  <ItemGroup>
    <Content Include="Resources\easysave_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  -->

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyLog\EasyLog.csproj" />
    <ProjectReference Include="..\CryptoSoft\CryptoSoft.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\easysave_cloud.ico" />
    <Resource Include="Resources\easysave_logo.png" />
    <Resource Include="Resources\easysave_logo_trimmed.png" />
  </ItemGroup>

</Project>
