<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CryptoSoft</AssemblyName>
    <RootNamespace>CryptoSoft</RootNamespace>
    <!-- Configurer la sortie pour utiliser le dossier output à la racine -->
    <OutputPath>..\output</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWindowsForms>true</UseWindowsForms>
    <!-- Permet de démarrer comme une application console quand nécessaire -->
    <StartupObject>CryptoSoft.Program</StartupObject>
  </PropertyGroup>

</Project>